/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.sidenav[_ngcontent-%COMP%] {\n    overflow: scroll;\n    width: auto;\n    border-right: none;\n}\n\n.sidenav-content[_ngcontent-%COMP%] {\n    margin-bottom: 0;\n}\n\n.clr-vertical-nav[_ngcontent-%COMP%]   .nav-link[_ngcontent-%COMP%]:hover, .clr-vertical-nav[_ngcontent-%COMP%]   .nav-link.active[_ngcontent-%COMP%] {\n    background-color: #fafafa;\n}\n\n\n\n.header[_ngcontent-%COMP%]    > .branding[_ngcontent-%COMP%]    > .nav-link[_ngcontent-%COMP%]    > .clr-icon[_ngcontent-%COMP%] {\n    height: 36px;\n    width: 36px;\n    margin-right: 12px;\n}'];
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map