/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.sidenav[_ngcontent-%COMP%] {\n    overflow: scroll;\n    width: auto;\n    border-right: none;\n}\n\n.sidenav-content[_ngcontent-%COMP%] {\n    margin-bottom: 0;\n}\n\n.clr-vertical-nav[_ngcontent-%COMP%]   .nav-link[_ngcontent-%COMP%]:hover, .clr-vertical-nav[_ngcontent-%COMP%]   .nav-link.active[_ngcontent-%COMP%] {\n    background-color: #fafafa;\n}\n\n\n\n.header[_ngcontent-%COMP%]    > .branding[_ngcontent-%COMP%]    > .nav-link[_ngcontent-%COMP%]    > .clr-icon[_ngcontent-%COMP%] {\n    height: 36px;\n    width: 36px;\n    margin-right: 12px;\n}\n\n\nclr-alert[_ngcontent-%COMP%] {\n    \n    margin: 25px;\n}\n\n\n\n.content-wrapper[_ngcontent-%COMP%] {\n    display: flex;\n    justify-content: space-between;\n    flex-wrap: wrap;\n}\n\n.content-wrapper[_ngcontent-%COMP%]   .col[_ngcontent-%COMP%] {\n    margin: 12px;\n    flex: 1 0 auto;\n    max-width: 400px;\n    min-width: 45%;\n}\n\n.col.inverse[_ngcontent-%COMP%] {\n    background-color: #313131;\n    padding: 12px;\n    flex: 1 0 auto;\n}\n\n\n.main-container[_ngcontent-%COMP%] {\n    width: 100%;\n}'];
//# sourceMappingURL=main.css.shim.ngstyle.js.map